app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from pickle import loads, dumps
from django.core.validators import MaxValueValidator, MinValueValidator

# Model: Amortecedor
# Utilizada para cardar informações do Amortecedor	
class Amortecedor (models.Model):

	amortecedor_codigo = models.CharField(max_length=45, primary_key=True, verbose_name='Código') 
	amortecedor_diametro_externo = models.FloatField(verbose_name='Tamanho do Diâmetro Externo')
	
	def __repr__(self):
		return self.amortecedor_codigo
	def __str__(self):
		return self.amortecedor_codigo

# Model: Teste
# Utilizada para criacao de uma instancia do teste da bancada
class Teste(models.Model):
		
	teste_id = models.AutoField(primary_key=True, verbose_name='ID')
	teste_nome = models.CharField(max_length=45, null = False, verbose_name='Nome')
	teste_quantidade_ciclo = models.IntegerField(null = True, verbose_name='Quantidade de Ciclo',default=5,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)])
	teste_observacoes = models.TextField(max_length=255, blank = True, verbose_name='Observações')
	teste_data_hora = models.DateTimeField(default=timezone.now, verbose_name='Data')
	amortecedor = models.ForeignKey(Amortecedor, on_delete=models.CASCADE)
	graficoTemperaturaTempo = models.BinaryField(null = True)
	graficoForcaTempo = models.BinaryField(null = True)
	graficoForcaDeslocamento = models.BinaryField(null = True)
	curso = models.FloatField(verbose_name='Tamanho do Curso')

	def getGraficoTemperaturaTempo(self):
		return loads(self.graficoTemperaturaTempo)
		
	def setGraficoTemperaturaTempo(self,lista):
		self.graficoTemperaturaTempo = dumps(lista)
		
	def getGraficoForcaTempo(self):
		return loads(self.graficoForcaTempo)
		
	def setGraficoForcaTempo(self,lista):
		self.graficoForcaTempo = dumps(lista)
		
	def getGraficoForcaDeslocamento(self):
		return loads(self.graficoForcaDeslocamento)
		
	def setrGaficoForcaDeslocamento(self,lista):
		self.graficoForcaDeslocamento = dumps(lista)
	
class TesteVelocidadeFixa(Teste):

	tipo_teste = "Velocidade Fixa"
	testeVF_velocidade = models.FloatField(null = True, verbose_name='Velocidade do Motor',default=5,
        validators=[
            MaxValueValidator(225),
            MinValueValidator(1)])	
	
class TesteVelocidadeVariavel(Teste):

	#testeVV_quantidade_velocidade = models.IntegerField(null = True, verbose_name='Quantidade de Velocidades')
	tipo_teste = "Velocidade Variável"
	arrayVelocidades = models.BinaryField(null = True)
	def getArrayVelocidades(self):
		return loads(self.arrayVelocidades)
		
	def setArrayVelocidades(self,lista):
		self.arrayVelocidades = dumps(lista)

app/templates/app/detalhamentoamortecedor.html
{% extends "app/layout.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><center>Testes Realizados com o Amortecedor:  {{amortecedor_atual.amortecedor_codigo}}</center></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                <b>Informações básicas</b>
            </div>

            <div class="panel-body">
                <div class="dataTable_wrapper">

                    <!--Tabela com o histórico dos testes -->                  
                    <table class="table table-striped table-bordered table-hover" id="dataTablesAmortecedor">
                      <thead>
                        <tr>
                            <th style="font-weight:bold; text-align: center;">ID</th>
                            <th style="font-weight:bold; text-align: center;">Nome</th>
                             <th style="font-weight:bold; text-align: center;">Tipo</th>
                            <th style="font-weight:bold; text-align: center;">Quantidade de Ciclos</th>
                            <th style="font-weight:bold; text-align: center;">Curso</th>
                            <th style="font-weight:bold; text-align: center;">Data e Hora</th>
                        </tr>
                      </thead>

                      <tbody>
                        {% for teste in amortecedor_testes %}
                            <tr>
                                <th style="text-align: center;">{{teste.teste_id}}</th>
                                <th style="text-align: center;"><a href="{% url 'detalharTeste' primary_key=teste.pk %}">{{teste.teste_nome}}</a></th> 
                                <th style="text-align: center;">{{teste.tipo_teste}}</th>
                                <th style="text-align: center;">{{teste.teste_quantidade_ciclo}}</th> 
                                <th style="text-align: center;">{{teste.curso}}</th> 

                                <th style="text-align: center;">{{teste.teste_data_hora}}</th>
                            </tr>
                        {% endfor %}
                     </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
        
                

{% endblock %}


{% block scripts %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#dataTablesAmortecedor').DataTable({
            language: {
                processing:     "Processando...",
                search:         "Busca:",
                lengthMenu:    "Visualizar _MENU_ entradas",
                info:           "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                infoEmpty:      "Mostrando 0 a 0 de 0 entradas",
                infoFiltered:   "(filtrando de _MAX_ total de entradas)",
                infoPostFix:    "",
                loadingRecords: "Carregando...",
                zeroRecords:    "Nenhum registro encontrado",
                emptyTable:     "Nenhum dado disponível na tabela",
                paginate: {
                    first:      "Primeiro",
                    previous:   "Anterior",
                    next:       "Próximo",
                    last:       "Ultimo"
                },
                aria: {
                    sortAscending:  "Ative para ordenar colunas de forma ascendente",
                    sortDescending: ": Ative para ordenar colunas de forma descendente"
                }
            }
        });
    });
</script>
    
<style type="text/css">
    ${demo.css}
</style>

{% endblock %}

app/templates/app/historico.html
{% extends "app/layout.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><center>Histórico de Testes</center></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                <b>Informações básicas</b>
            </div>

            <div class="panel-body">
                <div class="dataTable_wrapper">

                    <!--Tabela com o histórico dos testes -->                  
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                      <thead>
                        <tr>
                            <th style="font-weight:bold; text-align: center;">Nome</th>
                            <th style="font-weight:bold; text-align: center;">Tipo</th>
                            <th style="font-weight:bold; text-align: center;">Quantidade de Ciclos</th>
                            <th style="font-weight:bold; text-align: center;">Curso</th>
                            <th style="font-weight:bold; text-align: center";>Data e Hora</th>
                        </tr>
                      </thead>

                      <tbody>
                        {% for teste in lista_de_testes %}
                            <tr>
                                <th style="text-align: center;"><a href="{% url 'detalharTeste' primary_key=teste.pk %}">{{teste.teste_nome}}</a></th> 
                                <th style="text-align: center;">{{teste.tipo_teste}}</th>
                                <th style="text-align: center;">{{teste.teste_quantidade_ciclo}}</th> 
                                <th style="text-align: center;">{{teste.curso}}</th> 
                                <th style="text-align: center;">{{teste.teste_data_hora}}</th>
                            </tr>
                        {% endfor %}
                     </tbody>
                    </table>
                <!--/.Fim da tabela com o histórico dos testes --> 
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-8">
           
    </div>
</div>

{% endblock %}
{% block scripts%}
<script type="text/javascript">
    $(document).ready(function(){
        $('#dataTables-example').DataTable({
            language: {
                processing:     "Processando...",
                search:         "Busca:",
                lengthMenu:    "Visualizar _MENU_ entradas",
                info:           "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                infoEmpty:      "Mostrando 0 a 0 de 0 entradas",
                infoFiltered:   "(filtrando de _MAX_ total de entradas)",
                infoPostFix:    "",
                loadingRecords: "Carregando...",
                zeroRecords:    "Nenhum registro encontrado",
                emptyTable:     "Nenhum dado disponível na tabela",
                paginate: {
                    first:      "Primeiro",
                    previous:   "Anterior",
                    next:       "Próximo",
                    last:       "Ultimo"
                },
                aria: {
                    sortAscending:  "Ative para ordenar colunas de forma ascendente",
                    sortDescending: ": Ative para ordenar colunas de forma descendente"
                }
            }
        });
    });
</script>
{% endblock %}

app/templates/app/historicoAmortecedor.html
{% extends "app/layout.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><center>Histórico de Amortecedores</center></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                <b>Informações básicas</b>
            </div>

            <div class="panel-body">
                <!--Tabela com o histórico dos testes -->                        
                <table class="table table-striped table-bordered table-hover" id="dataTables">
                    <thead>
                        <tr>
                            <th style="font-weight:bold; text-align: center";>Código</th>
                            <th style="font-weight:bold; text-align: center">Diametro</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for amortecedor in lista_de_amortecedores %}
                            <tr>
                                <th style="text-align: center;"><a href="amortecedor/{{amortecedor.pk}}">{{amortecedor.amortecedor_codigo}}</a></th>
                                <th style="text-align: center;">{{amortecedor.amortecedor_diametro_externo}}</th>
                            </tr>
                            
                        {% endfor %}
                    <tbody>
                </table>
                <!--/.Fim da tabela com o histórico dos testes --> 
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-8">
           
    </div>
</div>

{% endblock %}

{% block scripts%}
<script type="text/javascript">
    $(document).ready(function(){
        $('#dataTables').DataTable({
            language: {
                processing:     "Processando...",
                search:         "Busca:",
                lengthMenu:    "Visualizar _MENU_ entradas",
                info:           "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                infoEmpty:      "Mostrando 0 a 0 de 0 entradas",
                infoFiltered:   "(filtrando de _MAX_ total de entradas)",
                infoPostFix:    "",
                loadingRecords: "Carregando...",
                zeroRecords:    "Nenhum registro encontrado",
                emptyTable:     "Nenhum dado disponível na tabela",
                paginate: {
                    first:      "Primeiro",
                    previous:   "Anterior",
                    next:       "Próximo",
                    last:       "Ultimo"
                },
                aria: {
                    sortAscending:  "Ative para ordenar colunas de forma ascendente",
                    sortDescending: ": Ative para ordenar colunas de forma descendente"
                }
            }
        });
    });
</script>
{% endblock %}

app/templates/app/iniciarTeste.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<form role="form" method="POST" name="FrmRecurso">
                {%csrf_token %}
                {{form.as_p}}
                 <!--<div class="">
                    <div class="form-group">
                        Nome:
                        <input text class="form-control" id="nome" name="nome" required ></text>
                    </div>
                    <div class="form-group">
                        Observacoes:
                        <textarea class="form-control" rows="5" cols="150" id="observacoes" name="observacoes" ></textarea>
                    </div>
                      {%csrf_token %}
                    <div class="form-group">
                        Tempo (minutos):
                        <input class="form-control" type="number" name="tempo" min="1" max="10" step="1" value="1" required/> 
                    </div>
               
                </div>-->
                    <div class="">
                        <input id="btnCriarNovaQuestao" class="btn btn-primary" type="submit" name="enviar" value="Iniciar" >
                    </div>
            </form>

{% endblock %}

app/templates/app/iniciarTesteVelocidadeFixa.html
{% extends "app/layout.html" %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><center>Teste por Velocidade Fixa</center></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <b>Informações básicas</b>
            </div>
            <div class="panel-body">
                <form id="myForm" role="form" method="POST" name="FrmRecurso" autocomplete="off">
                    {%csrf_token %}
                    
                    <!-- Formulário do Amortecedor -->
                    {{formArm.non_field_errors}}
                    <h4 class="page-header"><span class="span_h2">Amortecedor</span></h4>

                    <div class="form-group row">
                    {{formArm.amortecedor_codigo.errors}}
                        <label class="col-sm-2 form-control-label" for="id_amortecedor_codigo">Código:</label>
                        <div class="col-sm-3">
                            <input class="form-control" id="id_amortecedor_codigo" maxlength="45" name="amortecedor_codigo" type="text" placeholder="Insira o código do Amortecedor"/>
                            <p class="help-block">* Campo Obrigatório</p>
                        </div>
                         <div class="col-sm-7">
                            <p class="help-block" style="text-align: justify;">O código do amortecedor é o identificador único utilizado para buscar os testes realiados com diferentes amortecedor. Se estiver utilizando um amortecedor novo, defina um valor e o informe aqui, caso já tenha realizado outros testes com este amortecedor, insira o código cadastrado.</p>
                        </div>
                    </div>
                    
                     <div class="form-group row">
                        {{ form.amortecedor_diametro_externo.errors }}
                        <label class="col-sm-2 form-control-label" for="id_amortecedor_diametro_externo">Tamanho do Diâmetro Externo:</label>
                        <div class="col-xs-3">
                            <input class="form-control" id="id_amortecedor_diametro_externo" name="amortecedor_diametro_externo" type="number" value="10" size="2" maxlength="2" min="2" max="100"/>
                        </div>
                        <div class="col-sm-7">
                            <p class="help-block" style="text-align: justify;">Valor do Diametro Externo do Amortecedor dado em <span style="text-decoration:underline;">centímetros (cm)</span>, caso não o tenha, deixe o valor 0 como padrão.</p>
                        </div>
                    </div>


                    <!-- Formulário do Teste -->
                    {{ form.non_field_errors }}
                    <h4 class="page-header"><span class="span_h2">Teste</span></h4>
                    <div class="form-group row">
                        {{ form.teste_nome.errors }}
                        <label class="col-sm-2 form-control-label" for="id_teste_nome">Nome:</label>
                        <div class="col-sm-3">
                            <input class="form-control" id="id_teste_nome" maxlength="45" name="teste_nome" type="text" placeholder="Insira um nome para este Teste" />
                            <p class="help-block">* Campo Obrigatório</p>
                        </div>
                        <div class="col-sm-7">
                            <p class="help-block" style="text-align: justify;">O Nome do teste é utilizado para recuperar, durante uma busca, por testes já realizados. Utilize nomes significativos como: Teste_Amort510_Velocidade_225  </p>
                        </div>
                    </div>

                    <div class="form-group row">
                     {{ form.teste_quantidade_ciclo.errors }}
                        <label class="col-sm-2 form-control-label" for="id_teste_quantidade_ciclo">Quantidade de Ciclo:</label>
                        <div class="col-sm-3">
                            <select id="id_teste_quantidade_ciclo" name="teste_quantidade_ciclo" class="form-control">
                                <option value="10" selected="selected" style="width:132px;">10</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                            </select> 
                        </div>
                        <div class="col-sm-7">
                            <p class="help-block" style="text-align: justify;">A quantidade de ciclos define quantos rotações o motor deverá realizar para executar o teste. Assuma que para um ciclo, o motor deve rotacionar uma volta completa em seu eixo (Diametro do Eixo: 25cm)</p>
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        {{ form.amortecedor_curso.errors }}   
                        <label class="col-sm-2 form-control-label" for="id_amortecedor_curso">Curso:</label>
                        <div class="col-sm-3">
                            <select id="curso" name="curso" class="form-control">
                            <option value="10.0" selected="selected" style="width:132px;">10 cm</option>
                            <option value="12.5">12.5 cm</option>
                            <option value="15.0">15 cm</option>
                            </select> 
                        </div>
                        <div class="col-sm-7">
                            <p class="help-block" style="text-align: justify;">O curso é definido de acordo com deslocamento configurado no amortecedor. <span style="text-decoration:underline; color:red">CUIDADO:</span> Ao selecionar um valor, certifique-se, antes de iniciar o teste, que o curso da bancada está correpondente.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                     {{ form.testeVF_velocidade.errors }}
                        <label class="col-sm-2 form-control-label" for="id_testeVF_velocidade">Velocidade linear máxima:</label>
                        <div class="col-sm-3">
                            <select id="testeVF_velocidade" name="testeVF_velocidade" class="form-control">
                                <option value="175">175 mm/segundo</option>
                                <option value="200">200 mm/segundo</option>
                                <option value="225" selected="selected">225 mm/segundo</option>
                            </select>
                        </div>
                        <div class="col-sm-7">
                            <div id="box-toggle">
                                <p class="help-block" style="text-align: justify;">Este campo corresponde a velocidade que será utilizada na execução do teste. Você pode selecionar apenas 1 velocidade. A tabela, disponível no <i>link</i> a seguir, relaciona os valores das velocidades lineares com os valores das velocidades do motor.
                                <div class="tgl">
                                    <table class="velocidade">
                                        <tr class="table-velocidade">
                                            <th class="table-velocidade"></th>
                                            <th class="table-velocidade">Curso de 10cm</th>
                                            <th class="table-velocidade">Curso de 12,5cm</th>
                                            <th class="table-velocidade">Curso de 15cm</th>
                                        </tr>
                                        <tr class="table-velocidade">
                                            <td class="table-velocidade" colspan="4"> Velocidade Linear 225 mm/s</td>
                                        </tr>
                                        <tr class="table-velocidade">
                                            <td class="table-velocidade">Velocidade do<br>motor (rpm)</td>
                                            <td class="table-velocidade">1350</td>
                                            <td class="table-velocidade">1074,46</td>
                                            <td class="table-velocidade">873,78</td>
                                        </tr>
                                        <tr class="table-velocidade">
                                            <td class="table-velocidade" colspan="4">Velocidade Linear 200 mm/s</td>
                                        </tr>
                                        <tr class="table-velocidade">
                                            <td class="table-velocidade">Velocidade do<br>motor (rpm)</td>
                                            <td class="table-velocidade">1199,24</td>
                                            <td class="table-velocidade">955,15</td>
                                            <td class="table-velocidade">776,66</td>
                                        </tr>
                                        <tr class="table-velocidade">
                                            <td class="table-velocidade" colspan="4">Velocidade Linear 175 mm/s</td>
                                        </tr>
                                        <tr class="table-velocidade">
                                            <td class="table-velocidade">Velocidade do<br>motor (rpm)</td>
                                            <td class="table-velocidade">1049,38</td>
                                            <td class="table-velocidade">835,83</td>
                                            <td class="table-velocidade">679,54</td>
                                        </tr>
                                    </table>
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>
            
                    <div class="form-group row">
                    {{ form.teste_observacoes.errors }}
                        <label class="col-sm-2 form-control-label" for="id_teste_observacoes">Observações:</label>
                        <div class="col-sm-5">
                            <textarea cols="40" id="id_teste_observacoes" maxlength="255" name="teste_observacoes" rows="10" class="form-control" placeholder="Insira informações adicionais"></textarea>
                        </div>
                        <div class="col-md-5">
                            <p class="help-block" style="text-align: justify;">Insira aqui os valores que achar pertinentes para seu teste. </p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-offset-2 col-sm-10">
                            <center><input id="id_enviar" class="btn" type="submit" name="enviar" value="Iniciar Teste" style="margin:10px; width:275px; height: 50px"></center>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-8">
           
    </div>
</div>

{% endblock %}

{% block scripts %}

<script>

jQuery.fn.toggleText = function(a,b) {
return   this.html(this.html().replace(new RegExp("("+a+"|"+b+")"),function(x){return(x==a)?b:a;}));
}

$(document).ready(function(){
$('.tgl').before('<span>Clique aqui para exibir a tabela.</span>');
$('.tgl').css('display', 'none')
$('span', '#box-toggle').click(function() {
$(this).next().slideToggle('slow')
.siblings('.tgl:visible').slideToggle('fast');
// aqui começa o funcionamento do plugin
$(this).toggleText('exibir','ocultar')
.siblings('span').next('.tgl:visible').prev()
.toggleText('exibir','ocultar')
});
})

$.ajax({
    url: "/json/nomeAmortecedor",
    success: function(json) {
        
        $(function() {

            $( "#id_amortecedor_codigo" ).autocomplete({
                source: json.nomes,
                close: function(){
                    this.blur();
                }
            });
        });
    }
});


    $("#id_amortecedor_codigo").blur(function(){
         // Para fazer a consulta, removemos tudo o que não é número do valor informado pelo usuário
         var ar = this.value;

         var url = "/json/amortecedor/"+ar;
     
        $.getJSON(url, function(dadosRetorno){
             try{
                 // Insere os dados em cada campo

                 //$("#id_amortecedor_diametro_externo_"+dadosRetorno.amortecedor_diametro_externo).attr('checked', true);
                 //$("#id_amortecedor_curso_"+dadosRetorno.amortecedor_curso).attr('checked', true);
                 //$(':radio').attr('disabled', true);
                 if (dadosRetorno.erro) {
                     $("#id_amortecedor_diametro_externo").prop('readonly', false);
                     //$("#id_amortecedor_curso").prop('readonly', false);
                     //$(':radio').attr('disabled', false);
                 }else{
                     $("#id_amortecedor_diametro_externo").val(dadosRetorno.amortecedor_diametro_externo);
                     //$("#id_amortecedor_curso").val(dadosRetorno.amortecedor_curso);
                     $("#id_amortecedor_diametro_externo").prop('readonly', true);
                     //$("#id_amortecedor_curso").prop('readonly', true);
                 }
             }catch(ex){
             
             }
        });
     });
     
     
     function terminarLoaging() {
         $.LoadingOverlay("hide");
    }

    
};
     
</script>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <section id="loginForm">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Autenticação</h3>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username" class="col-md-2 control-label">Usuário</label>
                            <div class="col-md-10">
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_password" class="col-md-2 control-label">Senha</label>
                            <div class="col-md-10">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="hidden" name="next" value="/" />
                                <input id='id_entrar' type="submit" value="Entrar" class="btn" />
                            </div>
                        </div>
                        {% if form.errors %}
                        <p class="validation-summary-errors">O usuário ou senha está errado.</p>
                        {% endif %}
                    </form>
                </div>
            </div>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginParte.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-center">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-left">
        <li><a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out fa-fw"></i>Sair</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-left">
    <li><a href="{% url 'login' %}"><i class="fa fa-sign-in fa-fw"></i>Log in</a></li>
</ul>

{% endif %}